add-controllers to sprint-14 done
denis-repkov/java-shareit pull request #1
Opened 2024-12-02 12:42 UTC by denis-repkov

2024-12-03 07:16 UTC, z8q requested changes

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/CreateUserDto.java
> +    @Email(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", message = "Эл.почта некорректна")
Без регулярки, похоже будет допускаться использование большего количества 
спец символов `!#$%&'*+/=?^_{|}~.-`
Если сделать в таком виде  – `@Email(message = "Эл.почта некорректна")`

Добавил регулярку, чтобы использовали только `._%+-`?

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userMapper.map(updatedUser);
маппинг можно перенести в сервисный класс (больше пожелание),
чтобы привести логику в контроллере просто к
```JAVA
return userService.update(userId, userDto);
```

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    }
Если в контроллере появляется много логики, то он начинает походить уже на сервис
Лучше перенести

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        }
У аннотации RequestHeader внутри есть параметр required, он по умолчанию выставлен в true
то есть контроллер не будет принимать null userId, 
можно потестировать

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (newItemDto == null) {
У RequestBody тоже есть параметр required, он тоже true

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
Для сервисов нужно еще создать интерфейс
То есть будет ItemService -> ItemServiceImpl

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private synchronized int getCounter() {
мы пока работаем в рамках одного потока)

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private static int idCounter = 0;
есть ли необходимость делать счетчик статическим?

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        userRepository.remove(id);
в целом, можно обратиться к мапе в репозитории только один раз
метод remove у hash map возвращает объект, если такой был в мапе
если не было, то возвращается null
можно проверить это значение на null,
и если null –  бросить `throw new NotFoundException(USER_NOT_FOUND + id);`

2024-12-03 07:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    private static int idCounter = 0;
счетчики еще можно перенести на уровень дао,
потому что в последующих домашках будем использовать базы
и из сервисов нужно будет убирать логику по увеличению счетчика и setId

2024-12-03 08:13 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/user/dto/CreateUserDto.java
> +    @Email(regexp = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", message = "Эл.почта некорректна")
Да, мысль были именно такая - ограничить кол-во используемых спецсимволов при указании адреса эл.почты.
Сейчас почитал статьи по разрешённым спецсимволам и в принципе согласен с тем, что можно использовать более широкий набор (регулярку уберу)

2024-12-03 12:27 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private synchronized int getCounter() {
Убрал

2024-12-03 12:28 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userMapper.map(updatedUser);
Исправил

2024-12-03 12:29 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private static int idCounter = 0;
Согласен, убрал

2024-12-03 13:20 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        }
Так и есть - убрал лишнюю логику

2024-12-03 13:23 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (newItemDto == null) {
Убрал проверку на null

2024-12-03 13:34 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        userRepository.remove(id);
Исправил

2024-12-03 14:17 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
Добавил интерфейсы (ItemService и UserService), изменил названия классов реализации

2024-12-03 14:18 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    }
Поправил - теперь эта логика в сервисе

2024-12-03 14:37 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    private static int idCounter = 0;
Перенёс логику по увеличению счётчика в repository

2024-12-04 13:58 UTC, z8q approved these changes

2024-12-04 14:01 UTC, merged