add-bookings to sprint-15 done
denis-repkov/java-shareit pull request #2
Opened 2024-12-22 18:03 UTC by denis-repkov

2024-12-23 18:43 UTC, z8q requested changes

2024-12-23 18:43 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto create(@RequestHeader(HEADER_USER_PARAMETER) Long bookerId,
для методов стоит явно указывать модификаторы доступа,
в данном случае public

2024-12-23 18:43 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto save(CreateBookingDto dto, Long bookerId) {
методы, которые выполняют операции чтения и записи, можно обернуть в транзакцию
поставить на методом `@Transactional`

методы, в которых выполняется только чтение – `@Transactional(readOnly = true)`

Если этого не делать, то для каждого обращения к базе будет открываться и закрываться отдельная транзакция
например в этом методе save для вызовов userRepository.findById, itemRepository.findById и bookingRepository.save

2024-12-23 18:43 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemMapper.map(savedItem);
Можно рассмотреть такой вариант записи, но тут как больше нравится)
```JAVA
return userRepository.findById(ownerId)
    .map(owner -> itemMapper.map(itemDto, owner))
    .map(itemRepository::save)
    .map(itemMapper::map)
    .orElseThrow(() -> new NotFoundException(USER_NOT_FOUND + ownerId));
```

2024-12-23 18:43 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    ItemRequestRepository requestRepository;
private final

2024-12-24 09:08 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto create(@RequestHeader(HEADER_USER_PARAMETER) Long bookerId,
Исправил (не досмотрел, когда писал контроллер)

2024-12-24 09:09 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    ItemRequestRepository requestRepository;
Поправил

2024-12-24 09:21 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemMapper.map(savedItem);
Поправил на предложенный вариант

2024-12-24 11:19 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto save(CreateBookingDto dto, Long bookerId) {
Добавил аннотации @Transactional в методах классов реализации сервисов

2024-12-24 17:59 UTC, z8q approved these changes

2024-12-24 17:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    @Transactional(rollbackFor = {NotFoundException.class, WrongArgumentsException.class})
По умолчанию Spring отменяет транзакции только для unchecked исключений (то есть для подклассов RuntimeException и Error)
Похоже WrongArgumentsException и NotFoundException как раз наследуются от RuntimeException, то есть являются непроверяемыми (unchecked)

в rollbackFor можно их указывать, 
но параметр больше сделан для checked исключений, то есть тех, которые наследуются напрямую от Exception,
потому что по умолчанию транзакции для checked исключений не откатываются

2024-12-25 08:40 UTC, denis-repkov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    @Transactional(rollbackFor = {NotFoundException.class, WrongArgumentsException.class})
Убрал rollbackFor в аннотации Transaction для методов с непроверяемыми исключениями, которые наследуются от RuntimeException

2024-12-25 08:44 UTC, merged