add-item-requests-and-gateway to sprint-16 done
denis-repkov/java-shareit pull request #3
Opened 2024-12-27 23:44 UTC by denis-repkov

2024-12-28 19:03 UTC, z8q requested changes

2024-12-28 19:03 UTC, z8q commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +            @RequestBody ItemRequestDto dto
стоит добавить Valid

2024-12-28 19:45 UTC, denis-repkov commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +            @RequestBody ItemRequestDto dto
Упустил этот момент при разделении на 2 модуля - поправил

2024-12-29 16:07 UTC, z8q approved these changes

2024-12-29 16:30 UTC, merged